codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "90...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: auto
        threshold: 0.5%

ignore:
  - "simplecpreprocessor/__init__.py"
  - "simplecpreprocessor/__main__.py"
  - "simplecpreprocessor/tests"
  - "simplecpreprocessor/tests/*.py"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
