name: Prepare build environment
description: Common steps for both building and publishing
runs:
  using: "composite"
  steps:
  - run: |
      python -m venv .venv
      source .venv/bin/activate
      echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
      echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
      pip install -r requirements-dev.txt
    shell: bash
